"""
Given two strings s and t which consist of only lowercase letters. String t is
generated by random shuffling string s and then add one more letter at a random
position. Find the letter that was added in t.
"""
from common_funcs import stringToString


class Solution:
    def findTheDifference_counter(self, s: str, t: str) -> str:
        from collections import Counter
        return list(Counter(t) - Counter(s))[0]
    
    def findTheDifference_ord(self, s: str, t: str) -> str:
        diff = 0
        for i in range(len(s)):
            diff -= ord(s[i])
            diff += ord(t[i])
        diff += ord(t[-1])
        return chr(diff)
    
    def findTheDifference_xor(self, s: str, t: str) -> str:
        res = 0
        for c in s + t:
            res ^= ord(c)
        return chr(res)


def main():
    while True:
        try:
            line = input()
            s = stringToString(line)
            line = input()
            t = stringToString(line)
            
            sol = Solution()
            ret_cnt = sol.findTheDifference_counter(s, t)
            ret_ord = sol.findTheDifference_ord(s, t)
            ret_xor = sol.findTheDifference_xor(s, t)
            
            print(f"Solved using Python's Counter:    {ret_cnt}")
            print(f"Solved by adding/subtracting ord: {ret_ord}")
            print(f"Solved using xor:                 {ret_xor}")
            
        except StopIteration:
            break


if __name__ == '__main__':
    main()
